### ISSUE TITLE
New to Rust but....

### ISSUE THREAD

**Issue by rancheradminau** [chef/rs-chef-api#11]
Is this client pretty complete? Looking to re-write a Go app we use into something more minimalist and Rust is in my list as a language of choice.

I am essentially looking for knife operations to retrieve nodes per environment. Very simple stuff.

**Comment by thommay** [comment]
I would say that when PR #10 lands it'll be reasonably close to complete - at that point all the requests that one can make to the server are modeled, and then a little bit of work to wrap structs around the responses will remain, but that's sort of optional anyway.

**Comment by thommay** [comment]
That specific example would look like:
```rust
let api = ApiClient::from_credentials(None).unwrap();
let nodes = api.environments().environment("prod").nodes().get();
```

**Comment by thommay** [comment]
#10 just got merged to master and i'm in the process of publishing the crates now.
